version: "3.9"
services:
  user:
    build: .
    networks:
      - frontend
    restart: always
    command: -user u -pass p
    ports:
      - "51461:51461"
    expose:
      - "51461"

networks:
  frontend:
    driver: bridge