// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: 2ban.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *IPStringRequest) Reset() {
	*x = IPStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2ban_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPStringRequest) ProtoMessage() {}

func (x *IPStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file__2ban_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPStringRequest.ProtoReflect.Descriptor instead.
func (*IPStringRequest) Descriptor() ([]byte, []int) {
	return file__2ban_proto_rawDescGZIP(), []int{0}
}

func (x *IPStringRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type OKReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *OKReply) Reset() {
	*x = OKReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file__2ban_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OKReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OKReply) ProtoMessage() {}

func (x *OKReply) ProtoReflect() protoreflect.Message {
	mi := &file__2ban_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OKReply.ProtoReflect.Descriptor instead.
func (*OKReply) Descriptor() ([]byte, []int) {
	return file__2ban_proto_rawDescGZIP(), []int{1}
}

func (x *OKReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File__2ban_proto protoreflect.FileDescriptor

var file__2ban_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x32, 0x62, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0f,
	0x49, 0x50, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22,
	0x19, 0x0a, 0x07, 0x4f, 0x4b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x2c, 0x0a, 0x06, 0x49, 0x50,
	0x32, 0x62, 0x61, 0x6e, 0x12, 0x22, 0x0a, 0x02, 0x49, 0x50, 0x12, 0x10, 0x2e, 0x49, 0x50, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x4f,
	0x4b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x61, 0x70,
	0x69, 0x46, 0x6f, 0x72, 0x67, 0x52, 0x50, 0x43, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__2ban_proto_rawDescOnce sync.Once
	file__2ban_proto_rawDescData = file__2ban_proto_rawDesc
)

func file__2ban_proto_rawDescGZIP() []byte {
	file__2ban_proto_rawDescOnce.Do(func() {
		file__2ban_proto_rawDescData = protoimpl.X.CompressGZIP(file__2ban_proto_rawDescData)
	})
	return file__2ban_proto_rawDescData
}

var file__2ban_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file__2ban_proto_goTypes = []interface{}{
	(*IPStringRequest)(nil), // 0: IPStringRequest
	(*OKReply)(nil),         // 1: OKReply
}
var file__2ban_proto_depIdxs = []int32{
	0, // 0: IP2ban.IP:input_type -> IPStringRequest
	1, // 1: IP2ban.IP:output_type -> OKReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__2ban_proto_init() }
func file__2ban_proto_init() {
	if File__2ban_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__2ban_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__2ban_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OKReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__2ban_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__2ban_proto_goTypes,
		DependencyIndexes: file__2ban_proto_depIdxs,
		MessageInfos:      file__2ban_proto_msgTypes,
	}.Build()
	File__2ban_proto = out.File
	file__2ban_proto_rawDesc = nil
	file__2ban_proto_goTypes = nil
	file__2ban_proto_depIdxs = nil
}
